name = "vandamdinh-astro"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-07-27"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
